import rawCurrencies from '../data/currencies.json' with { type: 'json' };
import rawModPool from '../data/mod-pool.json' with { type: 'json' };
import rawMods from '../data/mods.json' with { type: 'json' };
import rawStats from '../data/stats.json' with { type: 'json' };
import { ModPoolIndex } from './modPool.js';
import type { CurrencyDataset, ModPoolDataset } from './schemas.js';
import type { EnrichmentContext } from './enrich.js';
import { ModIndex } from './modIndex.js';
import type { ModDataset, StatDataset } from './schemas.js';
import { StatIndex } from './statIndex.js';

/**
 * `@poe2/data` — the bundled knowledge base and the passes that use it.
 *
 * Datasets under `data/` are generated by the scripts in `scripts/` and
 * committed. Nothing here performs network I/O at runtime; regenerating is a
 * deliberate act, run once per league or major patch (ADR-005).
 */
export * from './schemas.js';
export * from './statIndex.js';
export * from './modIndex.js';
export * from './enrich.js';
export * from './crafting.js';
export * from './modPool.js';

/**
 * Datasets are asserted rather than parsed at startup.
 *
 * Validating ~11k entries with zod on every launch would cost tens of
 * milliseconds for files that cannot change between releases. The test suite
 * runs the schemas over them instead, which is where the check belongs.
 */
export const statsDataset = rawStats as StatDataset;
export const modsDataset = rawMods as ModDataset;
// Already structurally a CurrencyDataset — the annotation documents intent and
// keeps the export stable if the JSON's inferred shape ever narrows.
export const currenciesDataset: CurrencyDataset = rawCurrencies;
export const modPoolDataset = rawModPool as ModPoolDataset;

let poolIndex: ModPoolIndex | null = null;

/** Lazily built: 426 pools and ~2.5k modifier lookups, paid on first use. */
export function defaultModPool(): ModPoolIndex {
  poolIndex ??= new ModPoolIndex(modPoolDataset, modsDataset);
  return poolIndex;
}

let cached: EnrichmentContext | null = null;

/**
 * Lazily built, then shared. Construction is ~11k Map insertions, paid once on
 * the first analysed item rather than on every application launch.
 */
export function defaultKnowledgeBase(): EnrichmentContext {
  cached ??= {
    stats: new StatIndex(statsDataset),
    mods: new ModIndex(modsDataset),
  };
  return cached;
}
